export const TOKENS = {
  // auth
  USER_AUTH_REPO: Symbol('USER_AUTH_REPO'),
  PASSWORD_HASHER: Symbol('PASSWORD_HASHER'),
  TOKEN_SIGNER: Symbol('TOKEN_SIGNER'),

  // REPO
  USER_REPO: Symbol('USER_REPO'),
  BLOCK_REPO: Symbol('BLOCK_REPO'),
  FOLLOW_REPO: Symbol('FOLLOW_REPO'),
  FOLLOW_REQUEST_REPO: Symbol('FOLLOW_REQUEST_REPO'),
  POST_REPO: Symbol('POST_REPO'),

  // KAFKA
  KAFKA_SERVICE: Symbol('KAFKA_SERVICE'),
  POST_EVENT_PUBLISHER: Symbol('POST_EVENT_PUBLISHER'),
} as const;
