// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'src/_shared/infra/prisma/schema.prisma',
  migrations: {
    path: 'src/_shared/infra/prisma/migrations',
    seed: 'npx tsx src/_shared/infra/prisma/seed/run.ts',
  },
  datasource: {
    url: process.env['DATABASE_URL'],
  },
});
